- name: copy script swarm-agent-docker-prune.sh
  copy: src=swarm-agent-docker-prune.sh dest=/tmp mode=0755

- name: run script swarm-agent-docker-prune.sh
  command: "/tmp/swarm-agent-docker-prune.sh {{ groups['swarm-bootstrap-manager'][0] }}"
  async: 3600
  poll: 10
