---
- name: download filebeat
  get_url: 
    url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-5.5.1-darwin-x86_64.tar.gz
    checksum: md5:6297ad27d6ddea291a4594b199d2fa21
    dest: /tmp/filebeat.tar.gz

- unarchive:
    src: /tmp/filebeat.tar.gz
    dest: /tmp/

- file: 
    path: /tmp/filebeat
    state: absent

- name: copying over
  command: mv /tmp/filebeat-5.5.1-darwin-x86_64 /tmp/filebeat