---
- name: Ensure database is created
  postgresql_db: name={{ db_name }}
                login_host={{ db_host }}
                port={{ db_port }}
                login_user={{ db_admin_user }}
                login_password={{ db_admin_password }}
                encoding='{{ db_encoding }}'
                lc_collate='{{ db_lc_collate }}'
                lc_ctype='{{ db_lc_ctype }}'
                state=present

- name: Ensure user has access to the database
  postgresql_user: name={{ db_user }}
                  password={{ db_password }}
                  no_password_changes=true
                  priv=ALL
                  state=present
                  login_host={{ db_host }}
                  port={{ db_port }}
                  login_user={{ db_admin_user }}
                  login_password={{ db_admin_password }}
                  db={{ db_name }}