---
keycloak1_replicas: 1
keycloak1_reservation_memory: 768M
keycloak1_limit_memory: 1024M

keycloak2_replicas: 1
keycloak2_reservation_memory: 768M
keycloak2_limit_memory: 1024M
keycloak_admin_username: admin
keycloak_admin_initial_password: 
