postgresql_archive_dir: "{{ postgresql_data_dir }}/archive"
postgresql_max_wal_senders: 5
postgresql_wal_keep_segments: 32
postgresql_listen_address: '*'
postgresql_port: 5432

postgresql_master_global_config_options:
  - option: unix_socket_directories
    value: '{{ postgresql_unix_socket_directories | join(",") }}'
  - option: listen_addresses
    value: '{{ postgresql_listen_address }}'
  - option: port
    value: "{{ postgresql_port }}"
  - option: wal_level
    value: 'hot_standby'
  - option: max_wal_senders
    value: "{{ postgresql_max_wal_senders }}"
  - option: wal_keep_segments
    value: "{{ postgresql_wal_keep_segments }}"
  - option: archive_mode
    value: on
  - option: archive_command
    value: "cp %p {{ postgresql_archive_dir }}/%f"
