version: '3.1'

services:
  content_service:
    image: "{{hub_org}}/{{image_name}}:{{image_tag}}"
    deploy:
      replicas: {{ content_replicas | default(1) }}
      resources:
        reservations:
          memory: "{{ content_reservation_memory  | default('64M') }}"
        limits:
          memory: "{{ content_limit_memory | default('256M') }}"
    healthcheck:
      test: curl -f http://localhost:5000/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      /home/deployer/env/sunbird_content_service.env
    ports:
     - "5000:5000"
    networks:
      - application_default

networks:
  application_default:
    external: true
