# According to http://docs.ansible.com/ansible/latest/glossary.html#notify
# Handlers are run in the order they are listed, not in the order that they are notified.
# Don't change the order here
- name: reload daemon
  command: systemctl daemon-reload

- name: restart docker
  service: name=docker state=restarted