---
- name: restart filebeat
  service:
    name: filebeat
    state: restarted
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'

- name: restart filebeat
  command: ./filebeat -c filebeat.yml -d "publish"
  args:
    chdir: "{{filebeat.base_path}}"
  when: ansible_os_family == 'Darwin'