# See meta folder for curator installation
- name: Delete snapshots older than {{ es_snapshot_retention_days }} days
  shell: curator delete snapshots --repository {{ es_snapshot_repository }} --older-than {{ es_snapshot_retention_days }} --time-unit days
  async: 3600
  poll: 10
