- name: copy the template lock_shard
  template: src=lock_shard.j2 dest=/home/deployer/lock_shard.js mode=0777 

- name: run the template lock_shard
  become: yes
  shell: "mongo < /home/deployer/lock_shard.js"
  async: 15
  poll: 0


