- name: install zip
  become: yes
  apt: name=zip state=present

- include: stop_query.yml
  when: query is defined

- include: lock_replica.yml
  when: shard is defined

- include: lock_config.yml
  when: config is defined

- include: backup_config.yml
  when: config is defined

- include: backup_replica.yml
  when: shard is defined

- include: start_query.yml
  when: query is defined
