- name: copy the template start_balancer
  template: src=start_balancer.j2 dest=/home/deployer/start_balancer.js mode=0777 

- name: run the template start_balancer
  become: yes
  shell: mongo < /home/deployer/start_balancer.js
  async: 15
  poll: 0

