- name: copy the template stop_balancer
  template: src=stop_balancer.j2 dest=/home/deployer/stop_balancer.js mode=0777 

- name: run the template stop_balancer
  become: yes
  shell: mongo < /home/deployer/stop_balancer.js
  async: 15
  poll: 0

