---
- name: Remove keycloak2 service
  shell: "docker service rm keycloak2"
  ignore_errors: yes

- name: Deploy keycloak2 service
  shell: "docker service create --replicas {{ keycloak2_replicas | default(1) }} -p 8082:8080 --name keycloak2 --hostname keycloak2 --reserve-memory {{ keycloak2_reservation_memory |  default('768M') }} --limit-memory {{ keycloak2_limit_memory |  default('1024M') }} --secret postgresql_keycloak_pass --network application_default --env-file /home/deployer/env/sunbird_keycloak2.env {{hub_org}}/{{image_name}}:{{image_tag}}"
  args:
    chdir: /home/deployer/stack
