---
- name: Remove keycloak1 service
  shell: "docker service rm keycloak1"
  ignore_errors: yes

- name: Deploy keycloak1 service
  shell: "docker service create --replicas {{ keycloak1_replicas | default(1) }} -p 8085:8080 --name keycloak1 --hostname keycloak1 --reserve-memory {{ keycloak1_reservation_memory |  default('768M') }} --limit-memory {{ keycloak1_limit_memory |  default('1024M') }}  --network application_default --env-file /home/deployer/env/sunbird_keycloak1.env --secret postgresql_keycloak_pass {{hub_org}}/{{image_name}}:{{image_tag}}"
  args:
    chdir: /home/deployer/stack
