---
- name: Ensure env directory exists
  file:
    path: /home/deployer/env
    state: directory
    owner: root
    group: root

- name: Ensure stack directory exists
  file:
    path: /home/deployer/stack
    state: directory
    owner: root
    group: root

- name: Save stack file
  template: src=stack-adminutil.yml dest=/home/deployer/stack/stack-adminutil.yml mode=0644

- name: Deploy stack
  shell: "docker stack deploy -c stack-adminutil.yml adminutil"
  args:
    chdir: /home/deployer/stack
